### ISSUE TITLE
Unable to `mix compile` on MacOS M1

### ISSUE THREAD

**Issue by adam12** [elixir-sqlite/exqlite#293]
Hello,

First time trying exqlite. Running into this error (`mix compile` from repo root but also running into error with Phoenix):

```
==> exqlite
Downloading precompiled NIF to /Users/adam/Library/Caches/exqlite-nif-2.16-aarch64-apple-darwin-0.24.0.tar.gz
Error happened while installing exqlite from precompiled binary: "precompiled \"exqlite-nif-2.16-aarch64-apple-darwin-0.24.0.tar.gz\" does not exist or cannot download: :enoent".

Attempting to compile exqlite from source...
** (Mix) Could not compile with "make" (exit status: 8).
You need to have gcc and make installed. Try running the
commands "gcc --version" and / or "make --version". If these programs
are not installed, you will be prompted to install them.
```

Any suggestions?

```
Erlang/OTP 27 [erts-15.0.1]
Elixir (1.17.2)
Darwin 23.5.0 arm64 arm
```

**Comment by warmwaffles** [comment]
Yea I thought this might happen. 😢 

I have been trying to figure out precompile issues for M1-M3 Macs. Try to stick to `v0.23.0` for now.

https://github.com/elixir-sqlite/exqlite/tree/precompile-woes

**Comment by warmwaffles** [comment]
Alright @adam12 this should be fixed with `v0.24.1`

**Comment by adam12** [comment]
Looks like it worked. Much thanks. :+1:

I still can't compile locally from git checkout but I wonder if that's on me.

**Comment by warmwaffles** [comment]
It most likely is. You need to install some sort of C compiler. Usually `gcc` will work. Clang would also work as well. https://github.com/cocoa-xu/cc_precompiler/blob/c07f72380a2600d2582ae03c3ea88a400d84c647/lib/cc_precompiler.ex#L38-L51

If you have `CC` exported to clang or the gcc binary it should work.

**Comment by adam12** [comment]
I don't want to take a ton of your time on this, just curious if the underlying issue is how I'm attempting the compile.

Should `mix compile` work from a checked out repo? I notice that I had to do `mix elixir_make.checksum` to satisfy `Error happened while installing exqlite from precompiled binary: "missing checksum.exs file".`

I did confirm I have a version of clang on path - exporting `CC` to `clang` didn't appear to improve anything.

**Comment by warmwaffles** [comment]
I use `mix elixir_make.checksum --all` to pull down all of the checksums before I publish up with `mix hex.publish`

**Comment by adam12** [comment]
Just to close the loop on this, I had an issue today with `elixir_bcrypt` with the same error message when running `mix compile`.

Tracked it down to the Fish shell remembering a path update command I used months ago to manipulate the path to `make` for Cosmopolitan CC.

**Comment by warmwaffles** [comment]
`fish` shell mentioned. I use it too.
